export const epochManagerAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_roleManager", type: "address", internalType: "address" },
      { name: "_areaRegistry", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "epochCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "epochs",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "name", type: "string", internalType: "string" },
      { name: "location", type: "string", internalType: "string" },
      { name: "area", type: "uint8", internalType: "enum AreaRegistry.AreaType" },
      { name: "startTime", type: "uint64", internalType: "uint64" },
      { name: "endTime", type: "uint64", internalType: "uint64" },
      { name: "state", type: "uint8", internalType: "enum EpochManager.EpochState" },
      { name: "creator", type: "address", internalType: "address" },
      { name: "participantCount", type: "uint32", internalType: "uint32" },
      { name: "maxParticipants", type: "uint32", internalType: "uint32" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEpoch",
    inputs: [{ name: "epochId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct EpochManager.Epoch",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "name", type: "string", internalType: "string" },
          { name: "location", type: "string", internalType: "string" },
          { name: "area", type: "uint8", internalType: "enum AreaRegistry.AreaType" },
          { name: "startTime", type: "uint64", internalType: "uint64" },
          { name: "endTime", type: "uint64", internalType: "uint64" },
          { name: "state", type: "uint8", internalType: "enum EpochManager.EpochState" },
          { name: "creator", type: "address", internalType: "address" },
          { name: "participantCount", type: "uint32", internalType: "uint32" },
          { name: "maxParticipants", type: "uint32", internalType: "uint32" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEpochState",
    inputs: [{ name: "epochId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint8", internalType: "enum EpochManager.EpochState" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEpochArea",
    inputs: [{ name: "epochId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint8", internalType: "enum AreaRegistry.AreaType" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isEpochActive",
    inputs: [{ name: "epochId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createEpoch",
    inputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "location", type: "string", internalType: "string" },
      { name: "area", type: "uint8", internalType: "enum AreaRegistry.AreaType" },
      { name: "startTime", type: "uint64", internalType: "uint64" },
      { name: "endTime", type: "uint64", internalType: "uint64" },
      { name: "maxParticipants", type: "uint32", internalType: "uint32" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "activateEpoch",
    inputs: [{ name: "epochId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "closeEpoch",
    inputs: [{ name: "epochId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "finalizeEpoch",
    inputs: [{ name: "epochId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "EpochCreated",
    inputs: [
      { name: "epochId", type: "uint256", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "area", type: "uint8", indexed: true },
      { name: "startTime", type: "uint64", indexed: false },
      { name: "endTime", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "EpochStateChanged",
    inputs: [
      { name: "epochId", type: "uint256", indexed: true },
      { name: "oldState", type: "uint8", indexed: false },
      { name: "newState", type: "uint8", indexed: false },
    ],
  },
] as const;
